package com.g992.anhud

object OverlayBroadcasts {
    const val ACTION_OVERLAY_SETTINGS_CHANGED = "com.g992.anhud.ACTION_OVERLAY_SETTINGS_CHANGED"
    const val EXTRA_NAV_X_DP = "extra_nav_x_dp"
    const val EXTRA_NAV_Y_DP = "extra_nav_y_dp"
    const val EXTRA_SPEED_X_DP = "extra_speed_x_dp"
    const val EXTRA_SPEED_Y_DP = "extra_speed_y_dp"
    const val EXTRA_SPEEDOMETER_X_DP = "extra_speedometer_x_dp"
    const val EXTRA_SPEEDOMETER_Y_DP = "extra_speedometer_y_dp"
    const val EXTRA_CLOCK_X_DP = "extra_clock_x_dp"
    const val EXTRA_CLOCK_Y_DP = "extra_clock_y_dp"
    const val EXTRA_CONTAINER_X_DP = "extra_container_x_dp"
    const val EXTRA_CONTAINER_Y_DP = "extra_container_y_dp"
    const val EXTRA_CONTAINER_WIDTH_DP = "extra_container_width_dp"
    const val EXTRA_CONTAINER_HEIGHT_DP = "extra_container_height_dp"
    const val EXTRA_NAV_SCALE = "extra_nav_scale"
    const val EXTRA_SPEED_SCALE = "extra_speed_scale"
    const val EXTRA_SPEEDOMETER_SCALE = "extra_speedometer_scale"
    const val EXTRA_CLOCK_SCALE = "extra_clock_scale"
    const val EXTRA_NAV_ALPHA = "extra_nav_alpha"
    const val EXTRA_SPEED_ALPHA = "extra_speed_alpha"
    const val EXTRA_SPEEDOMETER_ALPHA = "extra_speedometer_alpha"
    const val EXTRA_CLOCK_ALPHA = "extra_clock_alpha"
    const val EXTRA_CONTAINER_ALPHA = "extra_container_alpha"
    const val EXTRA_NAV_ENABLED = "extra_nav_enabled"
    const val EXTRA_SPEED_ENABLED = "extra_speed_enabled"
    const val EXTRA_SPEEDOMETER_ENABLED = "extra_speedometer_enabled"
    const val EXTRA_CLOCK_ENABLED = "extra_clock_enabled"
    const val EXTRA_SPEED_LIMIT_ALERT_ENABLED = "extra_speed_limit_alert_enabled"
    const val EXTRA_SPEED_LIMIT_ALERT_THRESHOLD = "extra_speed_limit_alert_threshold"
    const val EXTRA_PREVIEW = "extra_preview"
    const val EXTRA_PREVIEW_TARGET = "extra_preview_target"
    const val EXTRA_PREVIEW_SHOW_OTHERS = "extra_preview_show_others"

    const val PREVIEW_TARGET_NAV = "nav"
    const val PREVIEW_TARGET_SPEED = "speed"
    const val PREVIEW_TARGET_SPEEDOMETER = "speedometer"
    const val PREVIEW_TARGET_CLOCK = "clock"
    const val PREVIEW_TARGET_CONTAINER = "container"
}
